version: '{branch}-{build}'

configuration:
- Release
- Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QT_PARAMS: -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017

    - GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QT_PARAMS: -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017_64

    - GENERATOR: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT_PARAMS: -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017
      ARCH: Win32
      
    - GENERATOR: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT_PARAMS: -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017_64
      ARCH: x64
      
init: []

before_build:
- md build
- cd build
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (cmake --config "%CONFIGURATION%" -G "%GENERATOR%" %QT_PARAMS% ..)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (cmake --config "%CONFIGURATION%" -G "%GENERATOR%" -A %ARCH% %QT_PARAMS% ..)

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- cd bin/%CONFIGURATION%
- CppGoogleTestStarter.exe --gtest_output=xml:test_results.xml
- powershell ../../../scripts/appveyor.ps1